// vue/src/components/select/Select.vue
<template>
    <select
            @change="handleOnChange"
            :value="selectedOption"
    >
        <option
                v-for="option in options"
                :key="option"
                :value="option"
        >
            {{option}}
        </option>
    </select>
</template>

<script>
  import Vue from 'vue'

  export default Vue.component('Select', {
    name: 'Select',
    props: {
      options: Array,
      onChange: Function,
      selectedOption: String,
    },
    methods: {
      handleOnChange: function ({target: {value}}) {
        this.$emit('onChange', value)
      },
    },
  })
</script>

// react/src/components/select/Select.js
import React from 'react'

export const Select = ({options, onChange, selectedOption}) => (
  <select onChange={onChange} value={selectedOption}>
    {
      options.map(x => (
        <option
          key={x}
          value={x}
        >
          {x}
        </option>
      ))
    }
  </select>
)
