// vue/src/components/queryBuilder/QueryBuilderGroup.vue
<template>
    <section class="query-builder-rule">
        <section>
            <Select
                    :options="allowedCombinators"
                    @onChange="handleCombinatorChanged"
                    :selectedOption="tree.combinator"
            />
            <Button @onClick="handleRuleAdded">+Rule</Button>
            <Button @onClick="handleGroupAdded">+Group</Button>
            <Button v-if="!isRoot" @onClick="handleNodeRemove">x</Button>
        </section>
        <section>
            <section v-for="rule in tree.rules">
                <template v-if="!rule.rules">
                    <QueryBuilderRule
                            :key="rule.id"
                            :rule="rule"
                            @onNodeChanged="handleNodeChanged"
                            @onNodeRemove="handleNodeRemove"
                    />
                </template>
                <template v-if="rule.rules">
                    <QueryBuilderGroup
                            :key="rule.id"
                            :tree="rule"
                            @onNodeRemove="handleNodeRemove"
                            @onNodeChanged="handleNodeChanged"
                            @onGroupAdded="handleGroupAdded"
                            @onRuleAdded="handleRuleAdded"
                    />
                </template>
            </section>
        </section>
    </section>
</template>

<script>
  import { ALLOWED_QUERY_COMBINATORS } from '../../queryBuilder'
  import Select from '../select/Select.vue'
  import Button from '../button/Button.vue'
  import QueryBuilderRule from './QueryBuilderRule.vue'

  export default {
    name: 'QueryBuilderGroup',
    props: {
      tree: Object,
      onNodeRemove: Function,
      onNodeChanged: Function,
      onGroupAdded: Function,
      onRuleAdded: Function,
      isRoot: Boolean
    },
    data: function () {
      return {
        allowedCombinators: ALLOWED_QUERY_COMBINATORS,
      }
    },
    methods: {
      handleCombinatorChanged: function (value) {
        const {tree} = this
        this.$emit('onNodeChanged', tree.id, {
          ...tree,
          combinator: value
        })
      },
      handleNodeChanged: function (id, newNode) {
        this.$emit('onNodeChanged', id, newNode)
      },
      handleRuleAdded: function (id) {
        const {tree} = this
        if (!id) {
          this.$emit('onRuleAdded', tree.id)
        } else {
          this.$emit('onRuleAdded', id)
        }
      },
      handleNodeRemove: function (id) {
        const {tree} = this
        if (!id) {
          this.$emit('onNodeRemove', tree.id)
        } else {
          this.$emit('onNodeRemove', id)
        }
      },
      handleGroupAdded: function (id) {
        const {tree} = this
        if (!id) {
          this.$emit('onGroupAdded', tree.id)
        } else {
          this.$emit('onGroupAdded', id)
        }
      },
    },
    components: {
      QueryBuilderRule
    }
  }
</script>

// react/src/app/queryBuilder/QueryBuilderGroup.js
import React, { PureComponent } from 'react'
import { ALLOWED_QUERY_COMBINATORS } from '../../queryBuilder'
import { Select } from '../../components/select/Select'
import { Button } from '../../components/button/Button'
import { QueryBuilderRule } from './QueryBuilderRule'

export class QueryBuilderGroup extends PureComponent {
  handleCombinatorChanged = ({target: {value}}) => {
    const {queryTree, onNodeChanged} = this.props
    onNodeChanged(queryTree.id, {
      ...queryTree,
      combinator: value,
    })
  }

  renderRule = (rule) => {
    const {
      onNodeChanged,
      onNodeRemove,
      onRuleAdded,
      onGroupAdded,
    } = this.props

    if (rule.rules) {
      return (
        <section
          key={rule.id}
          className="query-builder-group__rule"
        >
          <QueryBuilderGroup
            onNodeChanged={onNodeChanged}
            onNodeRemove={onNodeRemove}
            onRuleAdded={onRuleAdded}
            onGroupAdded={onGroupAdded}
            queryTree={rule}
          />
        </section>
      )
    }

    return (
      <section
        key={rule.id}
        className="query-builder-group__rule"
      >
        <QueryBuilderRule
          onNodeChanged={onNodeChanged}
          onNodeRemove={onNodeRemove}
          rule={rule}
        />
      </section>
    )
  }

  render () {
    const {
      onNodeRemove,
      onRuleAdded,
      onGroupAdded,
      isRoot,
      queryTree: {
        combinator,
        rules,
        id
      }
    } = this.props
    return (
      <section className="query-builder-group">
        <section className="query-builder-group__content">
          <Select
            options={ALLOWED_QUERY_COMBINATORS}
            selectedValue={combinator}
            onChange={this.handleCombinatorChanged}
          />
          <Button onClick={() => onRuleAdded(id)}>+Rule</Button>
          <Button onClick={() => onGroupAdded(id)}>+Group</Button>
          {
            !isRoot && <Button onClick={() => onNodeRemove(id)}>x</Button>
          }
        </section>
        <section className="query-builder-group__rules">
          {
            rules.map(this.renderRule)
          }
        </section>
      </section>
    )
  }
}
